name: Deploy website
on:
  push:
    branches:
      - master
jobs:
  job-name:
     runs-on: ubuntu-latest
     steps:
         - name: we will download our repository in ubuntu machine
           uses: actions/checkout@v4

         - name: login
           uses: docker/login-action@v3
           with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_TOKEN }}
          
         - name: Build and push Docker image
           uses: docker/build-push-action@v5
           with:
             context: .
             push: true
             tags: rg7121/flask-app:latest
        
