name: Deploy website
on:
  push:
    branches:
      - master
jobs:
  job-name:
     runs-on: ubuntu-latest
     steps:
         - name: we will download our repository in ubuntu machine
           uses: actions/checkout@v4
         - name: Build docker image
           run: docker build -t gurav-img .
         - name: login
           run: docker login -u rg7121 -p 
          

        
